version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "aps831"
    labels:
      - "enhancement"
    open-pull-requests-limit: 100
