---
version: "3"
env:
  DOPPLER_PROJECT: "development"
  DOPPLER_CONFIG: "github"
tasks:
  tool-versions:upgrade:repo:
    summary: Upgrade version in .tool-versions
    desc: Upgrade version in .tool-versions
    internal: true
    silent: true
    cmds:
      - |
        [[ "{{ .REPONAME }}" == "" ]] && REPONAME={{ .NAME }} || REPONAME={{ .REPONAME }}
        version=$(gh api -H "Accept: application/vnd.github+json" repos/{{ .OWNER }}/$REPONAME/releases/latest | jq .tag_name -r)
        version=${version//v}
        sed -i "s/{{ .NAME }}.*/{{ .NAME }} $version/g" .tool-versions
  tool-versions:upgrade:
    summary: Upgrade versions in .tool-versions
    desc: Upgrade versions in .tool-versions
    cmds:
      - task: tool-versions:upgrade:trivy
      - task: tool-versions:upgrade:task
      - task: tool-versions:upgrade:doppler
  tool-versions:upgrade:trivy:
    summary: Upgrade version of trivy in .tool-versions
    desc: Upgrade version of trivy .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: aquasecurity
          NAME: trivy
  tool-versions:upgrade:task:
    summary: Upgrade version of task in .tool-versions
    desc: Upgrade version of task .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: go-task
          NAME: task
  tool-versions:upgrade:doppler:
    summary: Upgrade version of doppler in .tool-versions
    desc: Upgrade version of doppler .tool-versions
    cmds:
      - task: tool-versions:upgrade:repo
        vars:
          OWNER: DopplerHQ
          REPONAME: cli
          NAME: doppler
  permissions:
    summary: Check permissions on workflows
    desc: Check permissions on workflows
    cmds:
      - npx --yes @pkgdeps/update-github-actions-permissions@latest --defaultPermissions read-all ".github/workflows/*.{yaml,yml}"
  pin-github-actions:
    summary: Pin Github actions
    desc: Pin Github actions
    silent: true
    cmds:
      - |
        [ -n "$DOPPLER_DEVELOPMENT_GITHUB_TOKEN" ] && export DOPPLER_TOKEN=$DOPPLER_DEVELOPMENT_GITHUB_TOKEN
        export GH_ADMIN_TOKEN=$(doppler secrets get GITHUB_TOKEN_PUBLIC_REPOS --plain)
        for file in .github/workflows/*
        do
          echo $GH_ADMIN_TOKEN
          #npx --yes pin-github-action@latest $file
        done
  semgrep:auto:
    summary: Run semgrep static analysis with auto config
    desc: Run semgrep static analysis with auto config
    silent: true
    cmds:
      - semgrep --config=auto .
  semgrep:security-audit:
    summary: Run semgrep static analysis with security-audit config
    desc: Run semgrep static analysis with security-audit config
    silent: true
    cmds:
      - semgrep --config=p/security-audit .
  semgrep:secrets:
    summary: Run semgrep static analysis with secrets config
    desc: Run semgrep static analysis with secrets config
    silent: true
    cmds:
      - semgrep --config=p/secrets .
  trivy:fs:
    summary: Run trivy fs check
    desc: Run trivy fs check
    silent: true
    cmds:
      - trivy fs .
  trivy:config:
    summary: Run trivy config check
    desc: Run trivy config check
    silent: true
    cmds:
      - trivy config .
