---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Bitbucket Mirror
on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
        default: aps831-github
        description: "User name of Bitbucket repository"
      repositoryname:
        required: true
        type: string
        description: "Repository name of Bitbucket repository"
    secrets:
      BITBUCKET_SSH_PRIVATE_KEY:
        required: true
        description: "Private ssh key to connect to Bitbucket repository"
jobs:
  check-for-no-ci-cd-run:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/check-for-no-ci-cd-run.yaml@master

  mirror:
    permissions:
      contents: read
    if: needs.check-for-no-ci-cd-run.outputs.continue == 'true'
    needs:
      - check-for-no-ci-cd-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3.6.0
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # pin@v1
        with:
          target_repo_url: git@bitbucket.org:${{ inputs.username }}/${{ inputs.repositoryname }}.git
          ssh_private_key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
