---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build package
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
    secrets:
      ACCESS_TOKEN:
        required: false
env:
  MAVEN_PHASE: "clean install"
  ENFORCER_FAIL: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # pin@v2

      - name: Build
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # pin@v3
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          pull: true
          push: false
          build-args: |
            MAVEN_PHASE=${{ env.MAVEN_PHASE }}
            ENFORCER_FAIL=${{ env.ENFORCER_FAIL }}
          secrets: |
            GITHUB_USER_REF=${{ github.actor }}
            GITHUB_TOKEN_REF=${{ secrets.ACCESS_TOKEN && secrets.ACCESS_TOKEN || 'password' }}
          cache-from: type=gha,scope=build
          cache-to: type=gha,scope=build,mode=max
          target: build

      - name: Extract target
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # pin@v3
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          push: false
          build-args: |
            MAVEN_PHASE=${{ env.MAVEN_PHASE }}
            ENFORCER_FAIL=${{ env.ENFORCER_FAIL }}
          secrets: |
            GITHUB_USER_REF=${{ github.actor }}
            GITHUB_TOKEN_REF=${{ secrets.ACCESS_TOKEN && secrets.ACCESS_TOKEN || 'password' }}
          cache-from: type=gha,scope=build
          outputs: type=local,dest=${{ inputs.working-directory }}/target
          target: target

      - name: Fail on failure of previous build step
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # pin@v3
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          push: false
          build-args: |
            MAVEN_PHASE=${{ env.MAVEN_PHASE }}
            ENFORCER_FAIL=${{ env.ENFORCER_FAIL }}
          cache-from: type=gha,scope=build
          target: status

      - name: Test summary
        if: always()
        uses: test-summary/action@62bc5c68de2a6a0d02039763b8c754569df99e3f # pin@v2
        with:
          paths: "${{ inputs.working-directory }}/target/**/TEST-*.xml"
