---
# yamllint disable rule:line-length
name: Build and Publish Terraform
on:
  workflow_call:
    inputs:
      branch-prerelease:
        description: "Branch to use for prereleases"
        required: false
        default: "prerelease"
        type: string
      branch-update-base:
        description: "Base name of temporary branch to use for creating update"
        required: false
        default: "chore/publish-update"
        type: string
      tag-prefix:
        description: "Prefix to use for version number when creating tag"
        required: false
        default: "v"
        type: string
      working-directory:
        description: "Working directory"
        required: false
        default: "."
        type: string
      paths:
        description: Newline separated list of paths within working directory
        required: true
        type: string
      templated-files:
        description: "Templated files to update with new tag"
        required: false
        default: ""
        type: string
      terraform-version:
        description: Terraform version
        required: true
        type: string
      release-on-default-branch:
        description: "Release on default branch"
        required: false
        default: true
        type: boolean
    secrets:
      ACCESS_TOKEN:
        description: "Access token"
        required: true
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    if: (github.triggering_actor != 'dependabot[bot]')
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # publish-workflow-control
      - uses: aps831/gh-actions/publish-workflow-control@master
        id: control
        with:
          tag-prefix: ${{ inputs.tag-prefix }}
          branch-prerelease: ${{ inputs.branch-prerelease }}
          branch-update-base: ${{ inputs.branch-update-base }}
          release-on-default-branch: ${{ inputs.release-on-default-branch }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # project-update-terraform
      - uses: aps831/gh-actions/project-update-terraform@master
        if: ${{ steps.control.outputs.update == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          working-directory: ${{ inputs.working-directory }}
          templated-files: ${{ inputs.templated-files }}
          branch-event: ${{ steps.control.outputs.branch-event }}
          branch-update: ${{ steps.control.outputs.branch-update }}
          persist-updates: ${{ steps.control.outputs.publish }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # build-terraform-project
      - uses: aps831/gh-actions/build-terraform-project@master
        if: ${{ steps.control.outputs.build == 'true' }}
        with:
          branch-build: ${{ steps.control.outputs.branch-build }}
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}
          paths: ${{ inputs.paths }}

      # project-update-cleanup
      - uses: aps831/gh-actions/project-update-cleanup@master
        if: ${{ failure() && steps.control.outputs.update == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          branch-event: ${{ steps.control.outputs.branch-event }}
          branch-update: ${{ steps.control.outputs.branch-update }}

      # github-release-publish
      - uses: aps831/gh-actions/github-release-publish@master
        if: ${{ steps.control.outputs.publish == 'true' }}
        id: release
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          branch-update: ${{ steps.control.outputs.branch-update }}
          prerelease: ${{ steps.control.outputs.prerelease }}
          draft: ${{ steps.control.outputs.draft }}
          build-artifacts-upload-name: ""
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # github-release-unpublish
      - uses: aps831/gh-actions/github-release-unpublish@master
        if: ${{ steps.control.outputs.unpublish == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # github-release-finalize
      - uses: aps831/gh-actions/github-release-finalize@master
        if: ${{ steps.control.outputs.finalize == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # project-merge-update-branch
      - uses: aps831/gh-actions/project-merge-update-branch@master
        if: ${{ steps.control.outputs.update == 'true' }}
        with:
          target-branch: ${{ steps.control.outputs.branch-publish }}
          source-branch: ${{ steps.control.outputs.branch-update }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # project-merge-publish-branch
      - uses: aps831/gh-actions/project-merge-publish-branch@master
        if: ${{ steps.control.outputs.finalize == 'true' }}
        with:
          target-branch: ${{ steps.control.outputs.branch-default }}
          source-branch: ${{ steps.control.outputs.branch-publish }}
