---
# yamllint disable rule:line-length
name: Build and Publish Nodejs in Docker Directory Artifact
on:
  workflow_call:
    inputs:
      branch-prerelease:
        description: "Branch to use for prereleases"
        required: false
        default: "prerelease"
        type: string
      branch-update-base:
        description: "Base name of temporary branch to use for creating update"
        required: false
        default: "chore/publish-update"
        type: string
      tag-prefix:
        description: "Prefix to use for version number when creating tag"
        required: false
        default: "v"
        type: string
      working-directory:
        description: "Working directory"
        required: false
        default: "."
        type: string
      templated-files:
        description: "Templated files to update with new tag"
        required: false
        default: ""
        type: string
      output-artifact-directory:
        description: Output directory of artifact
        required: false
        default: "dist"
        type: string
      output-sbom-directory:
        description: Output directory of sbom
        required: false
        default: "outputs/sbom"
        type: string
      output-checks-directory:
        description: Output directory of checks
        required: false
        default: "outputs/checks"
        type: string
      output-unit-tests-directory:
        description: Output directory of unit tests
        required: false
        default: "outputs/unit-tests"
        type: string
      output-coverage-directory:
        description: Output directory of coverage
        required: false
        default: "outputs/coverage"
        type: string
      output-integration-tests-directory:
        description: Output directory of integration tests
        required: false
        default: "outputs/integration-tests"
        type: string
      release-on-default-branch:
        description: "Create releases on default branch"
        required: false
        default: true
        type: boolean
    secrets:
      ACCESS_TOKEN:
        description: "Access token"
        required: true
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.triggering_actor }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ (github.event_name == 'push' && !contains(github.triggering_actor, '[bot]' )) || (github.event.issue.pull_request && (startsWith(github.event.comment.body, '.publish') || startsWith(github.event.comment.body, '.unpublish') || startsWith(github.event.comment.body, '.finalize'))) }}
    env:
      COMMENT_BODY: "${{ github.event.comment.body }}"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # deprecation warning
      - shell: bash
        run: echo "::warning file=build-and-publish-nodejs-in-docker-directory-artifact.yaml,title=DEPRECATED::Update the workflow to use v2"

      # publish-workflow-control
      - uses: aps831/gh-actions/publish-workflow-control@master
        id: control
        with:
          tag-prefix: ${{ inputs.tag-prefix }}
          branch-prerelease: ${{ inputs.branch-prerelease }}
          branch-update-base: ${{ inputs.branch-update-base }}
          release-on-default-branch: ${{ inputs.release-on-default-branch }}
          comment-body: "${{ env.COMMENT_BODY }}"
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # publish-workflow-control-start
      - uses: aps831/gh-actions/publish-workflow-control-start@master
        with:
          release-on-default-branch: ${{ inputs.release-on-default-branch }}
          build: ${{ steps.control.outputs.build }}
          publish: ${{ steps.control.outputs.publish }}
          finalize: ${{ steps.control.outputs.finalize }}
          unpublish: ${{ steps.control.outputs.unpublish }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # prevent issue_comment trigger

      # project-update-nodejs
      - uses: aps831/gh-actions/project-update-nodejs@master
        if: ${{ steps.control.outputs.update == 'true' }}
        with:
          version: ${{ steps.control.outputs.version-next }}
          working-directory: ${{ inputs.working-directory }}
          tag: ${{ steps.control.outputs.tag-version-next }}
          templated-files: ${{ inputs.templated-files }}
          branch-event: ${{ steps.control.outputs.branch-event }}
          branch-update: ${{ steps.control.outputs.branch-update }}
          persist-updates: ${{ steps.control.outputs.publish }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # build-nodejs-in-docker-directory-artifact
      - uses: aps831/gh-actions/build-nodejs-in-docker-directory-artifact@master
        if: ${{ steps.control.outputs.build == 'true' }}
        id: build
        with:
          branch-build: ${{ steps.control.outputs.branch-build }}
          working-directory: ${{ inputs.working-directory }}
          dockerfile: "Dockerfile"
          stage-build: "build"
          stage-output: "output"
          stage-status: "status"
          output-artifact-directory: ${{ inputs.output-artifact-directory }}
          output-sbom-directory: ${{ inputs.output-sbom-directory }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # output-and-upload-nodejs-test-outputs
      - uses: aps831/gh-actions/output-and-upload-nodejs-test-outputs@master
        if: ${{ always() }}
        with:
          working-directory: ${{ inputs.working-directory }}
          output-checks-directory: ${{ inputs.output-checks-directory }}
          output-unit-tests-directory: ${{ inputs.output-unit-tests-directory }}
          output-coverage-directory: ${{ inputs.output-coverage-directory }}
          output-integration-tests-directory: ${{ inputs.output-integration-tests-directory }}

      # project-update-cleanup
      - uses: aps831/gh-actions/project-update-cleanup@master
        if: ${{ failure() && steps.control.outputs.update == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          branch-event: ${{ steps.control.outputs.branch-event }}
          branch-update: ${{ steps.control.outputs.branch-update }}

      # github-release-publish
      - uses: aps831/gh-actions/github-release-publish@master
        if: ${{ steps.control.outputs.publish == 'true' }}
        id: release
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          branch-update: ${{ steps.control.outputs.branch-update }}
          prerelease: ${{ steps.control.outputs.prerelease }}
          draft: ${{ steps.control.outputs.draft }}
          build-artifacts-upload-name: ${{ steps.build.outputs.build-artifacts-release-upload-name }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # github-release-unpublish
      - uses: aps831/gh-actions/github-release-unpublish@master
        if: ${{ steps.control.outputs.unpublish == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # github-release-finalize
      - uses: aps831/gh-actions/github-release-finalize@master
        if: ${{ steps.control.outputs.finalize == 'true' }}
        with:
          tag: ${{ steps.control.outputs.tag-version-next }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # project-merge-update-branch
      - uses: aps831/gh-actions/project-merge-update-branch@master
        if: ${{ steps.control.outputs.update == 'true' }}
        with:
          target-branch: ${{ steps.control.outputs.branch-publish }}
          source-branch: ${{ steps.control.outputs.branch-update }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # project-merge-publish-branch
      - uses: aps831/gh-actions/project-merge-publish-branch@master
        if: ${{ steps.control.outputs.finalize == 'true' }}
        with:
          target-branch: ${{ steps.control.outputs.branch-default }}
          source-branch: ${{ steps.control.outputs.branch-publish }}

      # publish-workflow-control-end
      - uses: aps831/gh-actions/publish-workflow-control-end@master
        if: ${{ always() }}
        with:
          release-on-default-branch: ${{ inputs.release-on-default-branch }}
          build: ${{ steps.control.outputs.build }}
          publish: ${{ steps.control.outputs.publish }}
          finalize: ${{ steps.control.outputs.finalize }}
          unpublish: ${{ steps.control.outputs.unpublish }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # prevent issue_comment trigger
