# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build package
on: 
  workflow_call:
    inputs:
      java-version: 
        required: true
        type: string
      maven-version: 
        required: true
        type: string 
      working-directory: 
        required: false
        type: string
        default: "."
env:
    MAVEN_PHASE: "clean install"
    ENFORCER_FAIL: false        
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          pull: true
          push: false
          build-args: |
            MAVEN_PHASE=${{ env.MAVEN_PHASE }}
            MAVEN_VERSION=${{ inputs.maven-version }}
            JAVA_VERSION=${{ inputs.java-version }}
            ENFORCER_FAIL=${{ env.ENFORCER_FAIL }}
          cache-from: type=gha,scope=build        
          cache-to: type=gha,scope=build,mode=max
          target: build  
      
      - name: Extract target
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          push: false
          build-args: |
            MAVEN_PHASE=${{ env.MAVEN_PHASE }}
            MAVEN_VERSION=${{ inputs.maven-version }}
            JAVA_VERSION=${{ inputs.java-version }}
            ENFORCER_FAIL=${{ env.ENFORCER_FAIL }}
          cache-from: type=gha,scope=build        
          outputs: type=local,dest=${{ inputs.working-directory }}/target
          target: target
       
      - name: Fail on failure of previous build step
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/Dockerfile
          push: false
          build-args: |
            MAVEN_PHASE=${{ env.MAVEN_PHASE }}
            MAVEN_VERSION=${{ inputs.maven-version }}
            JAVA_VERSION=${{ inputs.java-version }}
            ENFORCER_FAIL=${{ env.ENFORCER_FAIL }}
          cache-from: type=gha,scope=build        
          target: status                       