---
name: "Check for No CI/CD Run"
on:
  workflow_call:
    outputs:
      continue:
        description: "Flag to indicate if CI/CD should run"
        value: ${{ jobs.check.outputs.continue }}
jobs:
  check:
    runs-on: ubuntu-latest
    # A measure to save billing minutes 
    if: (github.actor != 'dependabot[bot]')
    permissions:
      contents: read
      issues: read
      pull-requests: read
    outputs:
      continue: ${{ steps.result.outputs.continue }}
    steps:
      - name: Test for no_ci_cd_run label
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # pin@v6
        id: label
        with:
          result-encoding: string
          script: |
            var issue_number = undefined;
            var ref = context.ref
            var sha = context.sha
            if ('pull_request' in context.payload) {
              issue_number = context.payload.pull_request.number
            } else {
              const { data: issues } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo
              })
              issue_number = issues.filter(issue => issue.head.sha === sha).map(issue => issue.number)[0]
            }
            console.log("INFO: event " + context.eventName)
            console.log("INFO: sha: " + sha)
            console.log("INFO: ref: " + ref)
            console.log("INFO: issue number: " + issue_number)
            if (issue_number) {
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number
              })
              var norun = issue.labels.map(label => label.name).includes("no_ci_cd_run")
              console.log("INFO: looking up labels on issue")
              console.log("INFO: label 'no_ci_cd_run' found: " + norun)
              console.log("INFO: continue: " + !norun)
              return !norun
            } else {
              console.log("INFO: no issue to look up labels on")
              console.log("INFO: label 'no_ci_cd_run' found: false")
              console.log("INFO: continue: " + true)
              return true
            }

      - name: Output summary
        run: |
          echo "**Check for No CI/CD Run**" >> $GITHUB_STEP_SUMMARY
          echo "Continue: ${{ steps.label.outputs.result }}" >> $GITHUB_STEP_SUMMARY

      - name: Output result
        id: result
        run: echo "continue=${{ steps.label.outputs.result }}" >> $GITHUB_OUTPUT
