---
name: Delete old workflow runs
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  delete:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@99626ea7e2020a8ab987073a1e127e2597102694 # pin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 30
          keep_minimum_runs: 6
