---
name: Delete old workflow runs
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  delete:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@1544db1aad28a3bad01a5e942f7370f65fd46e52 # pin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 30
          keep_minimum_runs: 6
