---
name: Deployment Record Subscribe
on:
  workflow_call:
    inputs:
      env:
        description: Environment
        required: true
        type: string
      component:
        description: Component
        required: true
        type: string
      timestamp:
        description: Timestamp
        required: true
        type: string
      message:
        description: Deployment message
        required: true
        type: string
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    if: (github.triggering_actor != 'dependabot[bot]')
    steps:
      - uses: aps831/gh-actions/deployment-record-sub@feat/deployment-status
        with:
          env: ${{ inputs.env }}
          component: ${{ inputs.component }}
          timestamp: ${{ inputs.timestamp }}
          message: ${{ inputs.message }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
