---
name: Deployment Candidate Subscribe
on:
  workflow_call:
    inputs:
      version-identifier:
        description: Version identifier of deployment candidate
        required: true
        type: string
      component:
        description: Component
        required: true
        type: string
      envs:
        description: Array of deployment environments
        required: false
        default: "['']"
        type: string
      working-directory:
        description: Working directory
        required: false
        default: "."
        type: string
      tfvars-filename:
        description: Filename of tfvars files
        required: false
        default: "terraform.tfvars"
        type: string
      tfvars-var:
        description: Variable name in tfvars file
        required: true
        type: string
      tfvars-regex:
        description: Regex of value in tfvars file
        required: true
        type: string
      branch-update-base:
        description: Base name of temporary branch to use for creating update
        required: false
        default: "chore/publish-update"
        type: string
permissions:
  contents: write
  issues: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.triggering_actor }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    if: (github.triggering_actor != 'dependabot[bot]')
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envs) }}
    steps:
      - uses: aps831/gh-actions/deployment-candidate-sub@master
        with:
          version-identifier: ${{ inputs.version-identifier }}
          component: ${{ inputs.component }}
          env: ${{ matrix.env }}
          working-directory: ${{ inputs.working-directory }}
          tfvars-filename: ${{ inputs.tfvars-filename }}
          tfvars-var: ${{ inputs.tfvars-var }}
          tfvars-regex: ${{ inputs.tfvars-regex }}
          branch-update-base: ${{ inputs.branch-update-base }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
