---
name: Deployment Candidate Publish
on:
  workflow_call:
    inputs:
      version-identifier:
        description: Version identifier of deployment candidate
        required: true
        type: string
      component:
        description: Component
        required: true
        type: string
      deployment-candidate-target-owner:
        description: Target owner
        required: true
        type: string
      deployment-candidate-target-repo:
        description: Target repository
        required: true
        type: string
      deployment-candidate-target-workflow:
        description: Target workflow
        required: true
        type: string
      deployment-candidate-target-branch:
        description: Target branch
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        description: "Access token"
        required: true
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.triggering_actor }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != 'latest' && github.event.registry_package.package_version.container_metadata.tag.name != '' && !startsWith(github.event.registry_package.package_version.container_metadata.tag.name, 'sha256-') }}
    steps:
      - uses: aps831/gh-actions/deployment-candidate-pub@master
        with:
          version-identifier: ${{ inputs.version-identifier }}
          component: ${{ inputs.component }}
          target-owner: ${{ inputs.deployment-candidate-target-owner }}
          target-repo: ${{ inputs.deployment-candidate-target-repo }}
          target-workflow: ${{ inputs.deployment-candidate-target-workflow }}
          target-branch: ${{ inputs.deployment-candidate-target-branch }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
