---
# yamllint disable rule:line-length
name: Ensure SHA pinned actions
# yamllint disable-line rule:truthy
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.triggering_actor }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  pin:
    permissions:
      contents: read
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4.1.7

      - name: Ensure SHA pinned actions
        # yamllint disable-line rule:comments
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@74606c30450304eee8660aae751818321754feb1 # pin@v3.0.9
        with:
          allowlist: |
            aps831/workflows/.github/workflows
            aps831/workflows/.github/actions
            aps831/gh-actions
