---
# yamllint disable rule:line-length
name: Ensure SHA pinned actions
# yamllint disable-line rule:truthy
on:
  workflow_call:
jobs:
  check-for-no-ci-cd-run:
    uses: aps831/workflows/.github/workflows/check-for-no-ci-cd-run.yaml@master
    permissions:
      contents: read
      issues: read
      pull-requests: read

  harden_security:
    permissions:
      contents: read
    if: needs.check-for-no-ci-cd-run.outputs.continue == 'true'
    needs:
      - check-for-no-ci-cd-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - name: Ensure SHA pinned actions
        # yamllint disable-line rule:comments
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@f32435541e24cd6a4700a7f52bb2ec59e80603b1 # pin@v2.1.4
        with:
          allowlist: |
            aps831/workflows/.github/workflows
            aps831/workflows/.github/actions
