---
# yamllint disable rule:line-length
name: Ensure SHA pinned actions
# yamllint disable-line rule:truthy
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.triggering_actor }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  pin:
    permissions:
      contents: read
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4.1.6

      - name: Ensure SHA pinned actions
        # yamllint disable-line rule:comments
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@76d1d8e0b075d7190b5d59b86da91c7bdbcc99b2 # pin@v3.0.7
        with:
          allowlist: |
            aps831/workflows/.github/workflows
            aps831/workflows/.github/actions
            aps831/gh-actions
