---
# yamllint disable rule:line-length
name: Ensure SHA pinned actions
# yamllint disable-line rule:truthy
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  pin:
    permissions:
      contents: read
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin@v4.1.3

      - name: Ensure SHA pinned actions
        # yamllint disable-line rule:comments
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@19ebcb0babbd282ae1822a0b9c28f3f1f25cea45 # pin@v3.0.4
        with:
          allowlist: |
            aps831/workflows/.github/workflows
            aps831/workflows/.github/actions
            aps831/gh-actions
