---
# yamllint disable rule:line-length
name: Ensure SHA pinned actions
# yamllint disable-line rule:truthy
on:
  workflow_call:
jobs:
  check-for-no-ci-cd-run:
    uses: aps831/workflows/.github/workflows/check-for-no-ci-cd-run.yaml@master
    permissions:
      contents: read
      issues: read
      pull-requests: read

  harden_security:
    permissions:
      contents: read
    if: needs.check-for-no-ci-cd-run.outputs.continue == 'true'
    needs:
      - check-for-no-ci-cd-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3.6.0

      - name: Ensure SHA pinned actions
        # yamllint disable-line rule:comments
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@21991cec25093947ff3f62e4c223df0260c39944 # pin@v2.1.2
        with:
          allowlist: |
            aps831/workflows/.github/workflows
            aps831/workflows/.github/actions
