---
name: Generate Dev Container Image
on:
  workflow_call:
    inputs:
      devcontainer-name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      # github-branch-event
      - uses: aps831/gh-actions/github-branch-event@master
        id: branch-event
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # git-checkout
      - uses: aps831/gh-actions/git-checkout@master
        with:
          branch: ${{ steps.branch-event.outputs.branch-event }}

      # set up nodejs
      - uses: aps831/gh-actions/set-up-nodejs@master

      # login-github-ghcr
      - uses: aps831/gh-actions/login-github-ghcr@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # calculate repository
      - id: repository
        run: |
          REPOSITORY="$(echo "ghcr.io/${{ github.repository }}/${{ inputs.devcontainer-name }}:latest" | tr '[:upper:]' '[:lower:]')"
          echo "repository=$REPOSITORY" >> $GITHUB_OUTPUT

      # install dev-container-cli
      - run: npm install -g "@vscode/dev-container-cli"

      # create image
      - run: devcontainer build --image-name "${{ steps.repository.outputs.repository }}" "${{ inputs.devcontainer-name }}"

      - uses: aps831/gh-actions/docker-push@master
        with:
          image: ${{ steps.repository.outputs.repository }}
