---
name: Load Used Actions
on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        description: Access token
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  actions: read
jobs:
  used:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: devops-actions/github-action-load-used-actions@30bbabf70d01e23552442b9349e7d62b97ee7702 # pin@v1.3.5
        name: Load used actions
        id: load-actions
        with:
          PAT: ${{ secrets.ACCESS_TOKEN }}

      - name: Show json file
        shell: bash
        run: cat ${{ steps.load-actions.outputs.actions-file }}

      - name: Upload result file as artefact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # pin@v2
        with:
          name: actions-file
          path: actions.json
