---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NPM Audit
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  audit:
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5

      - name: Run audit
        working-directory: ${{ inputs.working-directory }}
        run: npm audit --production --audit-level=high > audit.txt

      - name: Output step summary
        if: ${{ always() }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "**NPM Audit Production Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat audit.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
