---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NPM Audit
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  audit:
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin@v4.1.3

      - name: Run audit
        working-directory: ${{ inputs.working-directory }}
        run: npm audit --production --audit-level=high > audit.txt

      - name: Output step summary
        if: ${{ always() }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "**NPM Audit Production Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat audit.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
