---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NPM Audit
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
jobs:
  audit:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2

      - name: Run audit
        working-directory: ${{ inputs.working-directory }}
        run: npm audit --production --audit-level=high > audit.txt

      - name: Output step summary
        if: ${{ always() }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "**NPM Audit Production Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat audit.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
