# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NPM Audit
on: 
  workflow_call:
jobs:
  audit:
    runs-on: ubuntu-latest    
    permissions: 
      contents: read
      issues: write 
    steps:
      
      - uses: actions/checkout@v2

      - name: Run audit        
        working-directory: code
        run: npm audit --production --audit-level=high > audit.txt

      - name: Create Github issue
        if: ${{ failure() }}
        working-directory: code
        run: gh issue create --title "Review NPM audit" --body 'Run `npm audit --production --audit-level=high`'  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: |
            code/audit.txt       
