# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NPM Audit
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
jobs:
  audit:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run audit
        working-directory: ${{ inputs.working-directory }}
        run: npm audit --production --audit-level=high > audit.txt

      - name: Create Github issue
        if: ${{ failure() && github.event_name == 'schedule' }}
        run: gh issue create --title "Review NPM audit" --body 'Run `npm audit --production --audit-level=high`'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: |
            ${{ inputs.working-directory }}/audit.txt
