---
name: Permissions Advisor
permissions:
  actions: read
on:
  workflow_call:
    inputs:
      name:
        description: "The name of the workflow file to analyze"
        required: true
        type: string
      runs:
        description: "How many last runs to analyze"
        required: false
        type: number
        default: 10
jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/advisor@e83639073897b68de235d81a783b2221cc13def7 # pin@v1
        with:
          name: ${{ inputs.name }}
          count: ${{ inputs.runs }}
