---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reminder
on:
  workflow_call:
    inputs:
      title:
        description: "Title of Github issue"
        required: true
        type: string
      body:
        description: "Body of Github issue"
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
        description: "Github access token"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.triggering_actor }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4.1.7

      - name: Create Github issue
        run: gh issue create --title ${{ inputs.title }} --body ${{ inputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
