---
name: Ensure SHA pinned actions (Run)
on:
  pull_request: {}
  push:
    branches:
      - "master"
permissions:
  contents: read
jobs:
  harden_security:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/ensure-sha-pinned-actions.yaml@master
