---
name: Trunk Check (Run)
on:
  pull_request: {}
permissions:
  contents: read
jobs:
  trunk:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/trunk.yaml@master
