---
name: Delete old workflow runs (Run)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  delete:
    permissions:
      actions: write
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/delete-workflow-runs.yaml@master
