---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Bitbucket Mirror (Run)
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
permissions:
  contents: read
jobs:
  mirror:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/bitbucket-mirror.yaml@master
    with:
      repositoryname: workflows
    secrets:
      BITBUCKET_SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
