---
name: Grype Fs Scan (Run)
on:
  pull_request: {}
  push:
    branches:
      - "master"
permissions:
  contents: read
jobs:
  scan:
    uses: aps831/workflows/.github/workflows/grype-fs-scan.yaml@master
