---
name: Dependency Review (Run)
on:
  pull_request:
permissions:
  contents: read
jobs:
  dependency-review:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/dependency-review.yaml@master
