---
name: Grype Fs Scan (Run)
on:
  pull_request: {}
  push:
    branches:
      - "master"
jobs:
  scan:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/grype-fs-scan.yaml@master
