# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Security Headers
on:
  workflow_call:
jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Create Github issue
        run: gh issue create --title "Check Security Headers" --body 'Check on https://observatory.mozilla.org/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
