---
name: Semgrep Static Analysis
on:
  workflow_call:
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2

      - name: Run semgrep
        run: semgrep ci --text > semgrep.txt
        env:
          SEMGREP_RULES: p/ci

      - name: Output step summary
        if: ${{ always() }}
        run: |
          echo "**Semgrep Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat semgrep.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
