---
name: Semgrep Static Analysis
on:
  workflow_call:
jobs:
  check-for-no-ci-cd-run:
    uses: aps831/workflows/.github/workflows/check-for-no-ci-cd-run.yaml@master
    permissions:
      contents: read
      issues: read
      pull-requests: read

  semgrep:
    name: Scan
    if: needs.check-for-no-ci-cd-run.outputs.continue == 'true'
    needs:
      - check-for-no-ci-cd-run
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3.6.0

      - name: Run semgrep
        run: semgrep ci --text > semgrep.txt
        env:
          SEMGREP_RULES: p/ci

      - name: Output step summary
        if: ${{ always() }}
        run: |
          echo "**Semgrep Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat semgrep.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
