---
name: Semgrep Static Analysis
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  semgrep:
    name: Scan
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin@v4.1.3

      - name: Run semgrep
        run: semgrep ci --text > semgrep.txt
        env:
          SEMGREP_RULES: p/ci

      - name: Output step summary
        if: ${{ always() }}
        run: |
          echo "**Semgrep Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat semgrep.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
