---
name: Semgrep Static Analysis
on:
  workflow_call:
jobs:
  semgrep:
    name: Scan
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0

      - name: Run semgrep
        run: semgrep ci --text > semgrep.txt
        env:
          SEMGREP_RULES: p/ci

      - name: Output step summary
        if: ${{ always() }}
        run: |
          echo "**Semgrep Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat semgrep.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
