---
name: Terraform docs
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
jobs:
  check-for-no-ci-cd-run:
    uses: aps831/workflows/.github/workflows/check-for-no-ci-cd-run.yaml@master

  docs:
    if: needs.check-for-no-ci-cd-run.outputs.continue == 'true'
    needs:
      - check-for-no-ci-cd-run
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3.5.3
        with:
          ref: ${{ github.ref }}

      - name: Render terraform docs
        id: render
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # pin@v1.0.0
        with:
          find-dir: ${{ inputs.working-directory }}
          output-file: TERRAFORM.md
          output-method: replace
          git-commit-message: "chore(release): update terraform docs [skip ci]"
          git-push: true
          git-push-user-name: ${{ github.actor }}
          git-push-user-email: ${{ github.actor }}@users.noreply.github.com
