---
name: Terraform docs
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  docs:
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
        with:
          ref: ${{ github.ref }}

      - name: Render terraform docs
        id: render
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # pin@v1.0.0
        with:
          find-dir: ${{ inputs.working-directory }}
          output-file: TERRAFORM.md
          output-method: replace
          git-commit-message: "chore(release): update terraform docs [skip ci]"
          git-push: true
          git-push-user-name: ${{ github.actor }}
          git-push-user-email: ${{ github.actor }}@users.noreply.github.com
