name: Terraform check
on:
  workflow_call:
    inputs:
      terraform-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: "."
env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.terraform-version }}
          terraform_wrapper: false

      - name: Create Terraform Plugin Cache Dir
        run: mkdir --parents $TF_PLUGIN_CACHE_DIR

      - name: Cache Terraform
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init -backend=false

      - name: Terraform format check
        working-directory: ${{ inputs.working-directory }}
        run: terraform fmt -check -recursive

      - name: Terraform validate
        working-directory: ${{ inputs.working-directory }}
        run: terraform validate
