name: Terraform docs
on:
  workflow_call: 
    inputs:
      working-directory: 
        required: false
        type: string
        default: "."   
jobs:
  docs:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    permissions: 
      contents: write      
      pull-requests: write    
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
      
    - name: Render terraform docs
      id: render
      uses: terraform-docs/gh-actions@v0.11.0      
      with:
        find-dir: ${{ inputs.working-directory }}
        output-file: TERRAFORM.md
        output-method: replace      

    - name: Commit updated terraform docs
      if: steps.render.outputs.num_changed != 0
      run: |
        git config --global user.name 'aps831-bot'
        git config --global user.email 'aps831-bot@users.noreply.github.com'
        git config advice.addIgnoredFile false
        find . -name 'TERRAFORM.md' | grep -v /.git/ | xargs git add
        git commit -m 'chore(release): update terraform docs [skip ci]'          
        git push
          