---
name: Transfer Image GH to GCP
on:
  workflow_call:
    inputs:
      gcp-project:
        description: "GCP project"
        required: true
        type: string
      gcp-region:
        description: "GCP region"
        required: true
        type: string
      image-from-ghcr:
        description: "Image from GitHub container registry"
        required: true
        type: string
      image-to-gcp:
        description: "Image to GCP artifact registry"
        required: true
        type: string
      gcp-registry-secret-id:
        description: "ID of GCP secret containing the registry"
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        description: "Access token"
        required: true
      COSIGN_PUBLIC_KEY:
        description: "Cosign public key"
        required: true
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        description: "GCP workload identity provider"
        required: true
      GCP_SERVICE_ACCOUNT:
        description: "GCP service account"
        required: true
permissions:
  id-token: write
  packages: read
jobs:
  transfer:
    runs-on: ubuntu-latest
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != 'latest' && !startsWith(github.event.registry_package.package_version.container_metadata.tag.name, 'sha256-') }}
    steps:
      # login-gcp
      - uses: aps831/gh-actions/login-gcp@master
        with:
          workload-identity-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # registry
      - uses: aps831/gh-actions/gcp-secret-get@master
        id: registry
        with:
          gcp-project: ${{ inputs.gcp-project }}
          secret-id: ${{ inputs.gcp-registry-secret-id }}

      # login-gcp-artifactregistry
      - uses: aps831/gh-actions/login-gcp-artifactregistry@master
        with:
          region: ${{ inputs.gcp-region }}

      # login-github-ghcr
      - uses: aps831/gh-actions/login-github-ghcr@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # github-packages-docker-push
      - uses: aps831/gh-actions/github-packages-docker-push@master
        with:
          image-from-ghcr: ${{ inputs.image-from-ghcr }}
          image-to: ${{ steps.registry.outputs.value }}/${{ inputs.image-to-gcp }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
