---
name: Trivy Image Scan Dispatch
on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        description: "Access token"
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  packages: read
jobs:
  packages:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.packages.outputs.images }}
    steps:
      - id: packages
        uses: aps831/gh-actions/github-find-latest-container-packages@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  scan:
    permissions:
      packages: read
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    needs: [packages]
    strategy:
      fail-fast: false
      matrix:
        images: ${{ fromJSON(needs.packages.outputs.images) }}
    steps:
      # login-github-ghcr
      - uses: aps831/gh-actions/login-github-ghcr@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # docker-pull
      - uses: aps831/gh-actions/docker-pull@master
        with:
          image: "ghcr.io/${{ matrix.images.owner }}/${{ matrix.images.name }}:${{ matrix.images.tag }}"

      # action-trivy-image-scan
      - uses: aps831/gh-actions/action-trivy-image-scan@master
        with:
          image: "ghcr.io/${{ matrix.images.owner }}/${{ matrix.images.name }}:${{ matrix.images.tag }}"
